name: flutter_flow_list
description: Flutter FlowList

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^4.0.1
  provider: ^4.0.5
  provider_architecture: ^1.0.6
  equatable: ^1.1.1
  cupertino_icons: ^0.1.3
  logger_flutter: ^0.7.1

  flutter_crashlytics: ^1.0.0
  flutter_local_notifications: ^1.4.1

  firebase_remote_config: ^0.3.0+3
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+3
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.4+2

  #  google_api_availability: ^2.0.0
  google_sign_in: ^4.4.1

  shared_preferences: ^0.5.6+3
  date_format: ^1.0.8

  image: ^2.1.4
  cached_network_image: ^2.1.0+1
  flutter_svg: ^0.17.4
  intl: ^0.16.1
  image_picker: 0.6.1+4
  flutter_picker: ^1.1.3
  flutter_spinkit: ^4.1.2+1

  giphy_client: ^0.2.0
  giphy_picker: ^1.0.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: 4.1.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/secrets.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
